---
# Source: fastapi/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: release-name-fastapi
data:
    MLFLOW_TRACKING_PASSWORD: "cGFzc3dvcmQ="
    MLFLOW_TRACKING_USERNAME: "YWRtaW4="
---
# Source: fastapi/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-fastapi
  labels:
    helm.sh/chart: fastapi-0.1.0
    app.kubernetes.io/name: fastapi
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: fastapi
    app.kubernetes.io/instance: release-name
---
# Source: fastapi/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-fastapi
  labels:
    helm.sh/chart: fastapi-0.1.0
    app.kubernetes.io/name: fastapi
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fastapi
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fastapi
        app.kubernetes.io/instance: release-name
    spec:
      imagePullSecrets:
        - name: gcr-creds
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: fastapi
          securityContext:
            {}
          image: "europe-west4-docker.pkg.dev/temperature-predictor-441809/temperature-prediction/temperature-prediction-fastapi:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}

          env:
          - name: ROOT_PATH
            value: /server
          - name: TRACKING_URI
            value: http://mlflow-service:8080
          - name: MLFLOW_TRACKING_PASSWORD
            valueFrom:
              secretKeyRef:
                name: release-name-fastapi
                key: MLFLOW_TRACKING_PASSWORD
          - name: MLFLOW_TRACKING_USERNAME
            valueFrom:
              secretKeyRef:
                name: release-name-fastapi
                key: MLFLOW_TRACKING_USERNAME
---
# Source: fastapi/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-fastapi
  labels:
    helm.sh/chart: fastapi-0.1.0
    app.kubernetes.io/name: fastapi
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: 
      http:
        paths:
          - path: /server(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: release-name-fastapi
                port:
                  number: 8000
