apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db-deployment
spec:
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres:14
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-volume
      volumes: 
      - name: postgres-volume
        persistentVolumeClaim:
            claimName: postgres-pvc

