apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
spec:
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      imagePullSecrets:
        - name: gcr-creds
      containers:
      - name: mlflow
        image: europe-west4-docker.pkg.dev/temperature-predictor-441809/temperature-prediction/temperature-prediction-mlflow:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
         - name: MLFLOW_ARTIFACT_STORE
           value: gs://mlflow-artifact-store1
         - name: GOOGLE_APPLICATION_CREDENTIALS
           value: "/etc/mlflow/credentials.json"
        volumeMounts: 
        - name: mlflow-server-secret
          readOnly: true
          mountPath: "/etc/mlflow"
      volumes:
        - name: mlflow-server-secret
          secret:
            secretName: mlflow-server-secret

