apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  labels:
    app: mlflow
spec:
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      imagePullSecrets:
        - name: gcr-creds
      containers:
      - name: mlflow
        image: europe-west4-docker.pkg.dev/temperature-predictor-441809/temperature-prediction/temperature-prediction-mlflow:latest
        imagePullPolicy: Always
        # resources:
        #   requests:
        #     memory: "503Mi"
        #     cpu: "619m"
        #   limits:
        #     memory: "503Mi"
        #     cpu: "619m"
        ports:
        - containerPort: 8080
        env:
         - name: MLFLOW_TRACKING_USERNAME
           valueFrom:
            secretKeyRef:
              name: mlflow-auth-secret
              key: MLFLOW_TRACKING_USERNAME
         - name: MLFLOW_TRACKING_PASSWORD
           valueFrom:
            secretKeyRef:
              name: mlflow-auth-secret
              key: MLFLOW_TRACKING_PASSWORD
         - name: MLFLOW_ARTIFACT_STORE
           value: gs://mlflow-artifact-store1
         - name: DB_HOST
           value: mlflow-postgres-service
         - name: POSTGRES_USER
           valueFrom: 
            secretKeyRef:
              name: postgres
              key: POSTGRES_USER
         - name: POSTGRES_PASSWORD
           valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_PASSWORD
         - name: POSTGRES_DB
           valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_DB
         - name: GOOGLE_APPLICATION_CREDENTIALS
           value: "/etc/mlflow/credentials.json"
        volumeMounts: 
        - name: mlflow-server-secret
          readOnly: true
          mountPath: "/etc/mlflow"
      volumes:
        - name: mlflow-server-secret
          secret:
            secretName: mlflow-server-secret

